# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://localhost:8080/user
Accept: application/json

###
GET http://localhost:8080/user/1
Accept: application/json

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "account": "user1",
  "name": "User",
  "email": "user1@email.net",
  "password": "1234"
}

###
PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "storedPath": "C:\\Users\\kimji\\IdeaProjects\\DGSW_WEB_0326\\upload\\profile\\2019\\04\\05c0a4c432-5b13-4ee6-940a-0c72c374c573_2019012201182400-57B4628D2267231D57E0FC1078C0596D.jpg",
  "originalPath": "2019012201182400-57B4628D2267231D57E0FC1078C0596D.jpg"
}

###{
###  "name": "Userr",
###  "email": "user11@email.net",
###  "pw": "12345"
###}

###
DELETE http://localhost:8080/user/1
Accept: application/json

###
GET http://localhost:8080/post
Accept: application/json

###
GET http://localhost:8080/post/1
Accept: application/json

###
POST http://localhost:8080/post
Content-Type: application/json

{
  "userId": 1,
  "content": "Content WAW"
}

###
PUT http://localhost:8080/post
Content-Type: application/json

{
  "id": 1,
  "content": "Putted Content"
}

###
DELETE http://localhost:8080/post/1
Accept: application/json

###